name: Build RPM and DEB Packages

on:
    # Trigger the workflow on push events to the main branch
    push:
        branches: [main]

jobs:
    build-rpm:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install RPM build tools
              run: |
                  sudo apt-get install -y rpm

            - name: Build RPM package
              run: |
                  cd $GITHUB_WORKSPACE/rpm
                  rpmbuild -ba calculatefiles.spec
                  cd ~/rpmbuild/RPMS/noarch/
                  sudo rpm -i --nodeps count_files-1.0-1.noarch.rpm

            - name: Execute script count_files
              run: |
                  cd ~/../../bin
                  sudo ./count_files.sh

            - name: Upload RPM package to artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: rpm-package
                  path: ~/rpmbuild/RPMS/noarch/count_files-1.0-1.noarch.rpm

    build-deb:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install DEB build tools
              run: |
                  sudo apt-get install debhelper build-essential -y

            - name: Create debian files
              run: |
                  cd $GITHUB_WORKSPACE
                  sudo chmod +x create-debian-files.sh
                  ./create-debian-files.sh

            - name: Check files av
              run: |
                  cd $GITHUB_WORKSPACE/debian
                  ls

            - name: Build DEB package
              run: |
                  cd $GITHUB_WORKSPACE
                  sudo dpkg-buildpackage -b --no-sign
                  cd ..
                  sudo dpkg -i countfiles_0.1-1_all.deb

            - name: Execute script count_files
              run: |
                  cd ~/../../bin
                  sudo ./count_files.sh

            - name: Upload DEB package to artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: deb-package
                  path: ~/work/testrepository/testrepository/countfiles_0.1-1_all.deb
