name: Build RPM and DEB Packages

on:
    # Trigger the workflow on push events to the main branch
    push:
        branches: [main]

jobs:
    build-rpm:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build and run Jenkins in Docker
              run: |
                  docker build -t lab-jenkins .
                  docker run -d -v $GITHUB_WORKSPACE:/workspace -p 8080:8080 --name lab-jenkins lab-jenkins

            - name: Install RPM build tools
              run: docker exec -u root lab-jenkins apt-get install -y rpm

            - name: Build RPM package
              run: |
                  docker exec -u root lab-jenkins /bin/bash -c "cd /workspace/rpm && rpmbuild -ba calculatefiles.spec"
                  docker exec -u root lab-jenkins /bin/bash -c "cd /root/rpmbuild/RPMS/noarch/ && rpm -i --nodeps count_files-1.0-1.noarch.rpm"

            - name: Execute script count_files
              run: docker exec -u root lab-jenkins /bin/bash -c "cd /bin && ./count_files.sh"

            - name: Copy RPM package to GitHub Actions runner
              run: |
                  docker exec -u root lab-jenkins /bin/bash -c "cd /root/rpmbuild/RPMS/noarch/ && ls"
                  docker cp lab-jenkins:/root/rpmbuild/RPMS/noarch/count_files-1.0-1.noarch.rpm $GITHUB_WORKSPACE/

            - name: Upload RPM package to artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: rpm-package
                  path: ~/work/labsOC/labsOC/count_files-1.0-1.noarch.rpm

            - name: Stop and remove Jenkins container
              run: docker stop lab-jenkins && docker rm lab-jenkins

    build-deb:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build and run Jenkins in Docker
              run: |
                  docker build -t lab-jenkins .
                  docker run -d -v $GITHUB_WORKSPACE:/workspace -p 8080:8080 --name lab-jenkins lab-jenkins

            - name: Install DEB build tools
              run: docker exec -u root lab-jenkins apt-get install -y debhelper build-essential

            - name: Create debian files
              run: |
                  docker exec -u root lab-jenkins /bin/bash -c "cd /workspace && chmod +x create-debian-files.sh"
                  docker exec -u root lab-jenkins /bin/bash -c "cd /workspace && ./create-debian-files.sh"

            - name: Check files av
              run: |
                  docker exec -u root lab-jenkins /bin/bash -c "cd /workspace/debian && ls"

            - name: Build DEB package
              run: |
                  docker exec -u root lab-jenkins /bin/bash -c "cd /workspace && dpkg-buildpackage -b --no-sign"
                  docker exec -u root lab-jenkins /bin/bash -c "ls"
                  docker exec -u root lab-jenkins /bin/bash -c "dpkg -i countfiles_0.1-1_all.deb"

            - name: Execute script count_files
              run: |
                  docker exec -u root lab-jenkins /bin/bash -c "cd /bin && ./count_files.sh"

            - name: Copy DEB package to GitHub Actions runner
              run: |
                  docker cp lab-jenkins:countfiles_0.1-1_all.deb $GITHUB_WORKSPACE/

            - name: Upload DEB package to artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: deb-package
                  path: ~/work/labsOC/labsOC/countfiles_0.1-1_all.deb
